variables:
  GIT_STRATEGY: clone

stages:
  - test

# -----------------------------
# 1) CI TESTS (run in GitLab)
# -----------------------------
ci_tests:
  stage: test
  image: python:3.11

  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - echo "=== CI DIRECTORY STRUCTURE ==="
    - ls -R .
    - pytest -m "not hil" -v --junitxml=report.xml

  artifacts:
    reports:
      junit: report.xml
    paths:
      - report.xml
    expire_in: 1 week

  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip

# -----------------------------------------
# 2) HIL TESTS (run ONLY on your laptop)
# -----------------------------------------
hil_tests:
  stage: test
  tags:
    - esp32        # This ensures GitLab sends the job to YOUR laptop
  script:
    - pytest -m hil -v --junitxml=hil_report.xml

  artifacts:
    reports:
      junit: hil_report.xml
    paths:
      - hil_report.xml
    expire_in: 1 week
