[platformio]
default_envs = prod

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@^6.21.2
    knolleary/PubSubClient
    mikalhart/TinyGPSPlus
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    mcci-catena/MCCI LoRaWAN LMIC library@^5.0.1
    h2zero/NimBLE-Arduino

[env:prod]
build_flags =
    -DHIL_TEST_MODE=0
    -O2

; FIXED: include src and ALL subfolders
src =
    +<src/>
    +<src/**>
    -<hil/>

[env:hil_test]
build_flags =
    -DHIL_TEST_MODE=1

src =
    +<hil/>
    -<src/>
